# Generated by Django 2.0.6 on 2018-06-06 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name='title')),
                ('author', models.CharField(db_index=True, max_length=256, verbose_name='author')),
                ('ISBN', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('publish_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='publish date')),
            ],
            options={
                'verbose_name_plural': 'books',
                'verbose_name': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, editable=False, max_length=256, verbose_name='title')),
                ('author', models.CharField(db_index=True, editable=False, max_length=256, verbose_name='author')),
                ('action', models.CharField(db_index=True, editable=False, max_length=16, verbose_name='action')),
                ('change_field', models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, verbose_name='change field')),
                ('old_value', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='old value')),
                ('new_value', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='new value')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created date/time')),
            ],
            options={
                'verbose_name_plural': 'book logs',
                'verbose_name': 'book log',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(editable=False, max_length=2048, verbose_name='request')),
                ('parameters', models.CharField(editable=False, max_length=2048, verbose_name='parametres')),
                ('meta', models.CharField(editable=False, max_length=2048, verbose_name='meta')),
                ('cookies', models.CharField(editable=False, max_length=2048, verbose_name='cookies')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created date/time')),
            ],
            options={
                'verbose_name_plural': 'request logs',
                'verbose_name': 'request log',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
