# Generated by Django 2.0.6 on 2018-06-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklog',
            name='change_field',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='old_value',
        ),
        migrations.AddField(
            model_name='booklog',
            name='new_values',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='new values'),
        ),
        migrations.AddField(
            model_name='booklog',
            name='old_values',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='old values'),
        ),
    ]
